export interface MachineBlueprint {
  readonly status: "implemented" | "planned";
  readonly initial: string;
  readonly states: readonly string[];
  readonly events: readonly string[];
  readonly failureStates: readonly string[];
}

export const rewriteMachineMap = {
  appShell: {
    status: "planned",
    initial: "bootstrapping",
    states: ["bootstrapping", "unauthenticated", "ready", "fatal"],
    events: [
      "BOOTSTRAP.SUCCEEDED",
      "BOOTSTRAP.FAILED",
      "AUTH.BECAME_ANONYMOUS",
      "AUTH.BECAME_AUTHENTICATED",
      "ROUTE.REQUESTED",
      "FATAL.ACKNOWLEDGED",
    ],
    failureStates: ["fatal"],
  },
  auth: {
    status: "implemented",
    initial: "bootstrapping",
    states: [
      "bootstrapping",
      "anonymous",
      "redirecting",
      "authenticated",
      "loggingOut",
      "expired",
      "failure",
    ],
    events: [
      "SESSION.RESTORED",
      "SESSION.MISSING",
      "LOGIN.REQUESTED",
      "LOGIN.REDIRECTED",
      "SESSION.EXPIRED",
      "LOGOUT.REQUESTED",
      "LOGOUT.SUCCEEDED",
      "LOGOUT.FAILED",
      "AUTH.FAILED",
      "FAILURE.ACKNOWLEDGED",
    ],
    failureStates: ["expired", "failure"],
  },
  connectivity: {
    status: "planned",
    initial: "online",
    states: ["online", "offline"],
    events: ["BROWSER.WENT_ONLINE", "BROWSER.WENT_OFFLINE"],
    failureStates: [],
  },
  camera: {
    status: "planned",
    initial: "idle",
    states: [
      "idle",
      "unsupported",
      "requestingPermission",
      "ready",
      "scanning",
      "denied",
      "failure",
    ],
    events: [
      "CAMERA.START_REQUESTED",
      "CAMERA.PERMISSION_GRANTED",
      "CAMERA.PERMISSION_DENIED",
      "CAMERA.READY",
      "CAMERA.CODE_DETECTED",
      "CAMERA.STOP_REQUESTED",
      "CAMERA.FAILED",
    ],
    failureStates: ["unsupported", "denied", "failure"],
  },
  scanSession: {
    status: "implemented",
    initial: "idle",
    states: [
      "idle",
      "lookingUp",
      "unknown",
      "labeling.editing",
      "labeling.parsing",
      "labeling.submitting",
      "interacting.instanceReady",
      "interacting.instanceSubmitting",
      "interacting.bulkReady",
      "interacting.bulkEventParsing",
      "interacting.bulkEventSubmitting",
      "interacting.bulkSplitParsing",
      "interacting.bulkSplitSubmitting",
      "failure.lookup",
      "failure.assign",
      "failure.event",
      "failure.split",
    ],
    events: [
      "LOOKUP.REQUESTED",
      "LOOKUP.UNKNOWN",
      "LOOKUP.LABEL",
      "LOOKUP.INSTANCE",
      "LOOKUP.BULK",
      "LOOKUP.FAILED",
      "UNKNOWN.PROMOTED_TO_INTAKE",
      "ASSIGN.PARSE_REQUESTED",
      "ASSIGN.SUBMIT_REQUESTED",
      "ASSIGN.SUCCEEDED",
      "ASSIGN.FAILED",
      "EVENT.PARSE_REQUESTED",
      "EVENT.SUBMIT_REQUESTED",
      "EVENT.SUCCEEDED",
      "EVENT.FAILED",
      "SPLIT.PARSE_REQUESTED",
      "SPLIT.SUBMIT_REQUESTED",
      "SPLIT.SUCCEEDED",
      "SPLIT.FAILED",
      "SCAN.CLEAR_REQUESTED",
    ],
    failureStates: [
      "failure.lookup",
      "failure.assign",
      "failure.event",
      "failure.split",
    ],
  },
  bulkQueue: {
    status: "implemented",
    initial: "empty",
    states: ["empty", "ready", "submitting", "failed"],
    events: [
      "QUEUE.ACTION_CHANGED",
      "QUEUE.ROW_ACCEPTED",
      "QUEUE.ROW_REJECTED",
      "QUEUE.ROW_DECREMENT_REQUESTED",
      "QUEUE.ROW_REMOVE_REQUESTED",
      "QUEUE.CLEAR_REQUESTED",
      "QUEUE.SUBMIT_REQUESTED",
      "QUEUE.SUBMIT_SUCCEEDED",
      "QUEUE.SUBMIT_FAILED",
    ],
    failureStates: ["failed"],
  },
  inventoryRoute: {
    status: "planned",
    initial: "idle",
    states: ["idle", "loading", "ready", "expanding", "failure"],
    events: [
      "INVENTORY.LOAD_REQUESTED",
      "INVENTORY.LOAD_SUCCEEDED",
      "INVENTORY.LOAD_FAILED",
      "INVENTORY.FILTER_CHANGED",
      "INVENTORY.EXPAND_REQUESTED",
      "INVENTORY.EXPAND_SUCCEEDED",
      "INVENTORY.EXPAND_FAILED",
    ],
    failureStates: ["failure"],
  },
  activityRoute: {
    status: "planned",
    initial: "idle",
    states: ["idle", "loading", "ready", "failure"],
    events: [
      "ACTIVITY.LOAD_REQUESTED",
      "ACTIVITY.LOAD_SUCCEEDED",
      "ACTIVITY.LOAD_FAILED",
    ],
    failureStates: ["failure"],
  },
  batchAdmin: {
    status: "planned",
    initial: "idle",
    states: [
      "idle",
      "editing",
      "parsing",
      "submitting",
      "downloadingLabels",
      "success",
      "failure",
    ],
    events: [
      "BATCH.EDITED",
      "BATCH.PARSE_REQUESTED",
      "BATCH.SUBMIT_REQUESTED",
      "BATCH.SUBMIT_SUCCEEDED",
      "BATCH.DOWNLOAD_REQUESTED",
      "BATCH.DOWNLOAD_SUCCEEDED",
      "BATCH.FAILED",
    ],
    failureStates: ["failure"],
  },
  mergeAdmin: {
    status: "planned",
    initial: "idle",
    states: [
      "idle",
      "selectingSource",
      "searching",
      "selectingDestination",
      "confirming",
      "submitting",
      "success",
      "failure",
    ],
    events: [
      "MERGE.SOURCE_SELECTED",
      "MERGE.SEARCH_REQUESTED",
      "MERGE.SEARCH_SUCCEEDED",
      "MERGE.SEARCH_FAILED",
      "MERGE.DESTINATION_SELECTED",
      "MERGE.CONFIRM_REQUESTED",
      "MERGE.SUBMIT_REQUESTED",
      "MERGE.SUBMIT_SUCCEEDED",
      "MERGE.APPROVE_AS_IS_REQUESTED",
      "MERGE.APPROVE_AS_IS_SUCCEEDED",
      "MERGE.FAILED",
    ],
    failureStates: ["failure"],
  },
  syncAdmin: {
    status: "planned",
    initial: "unavailable",
    states: [
      "unavailable",
      "idle",
      "draining",
      "backfilling",
      "retrying",
      "success",
      "failure",
    ],
    events: [
      "SYNC.STATUS_LOADED",
      "SYNC.DRAIN_REQUESTED",
      "SYNC.DRAIN_SUCCEEDED",
      "SYNC.BACKFILL_REQUESTED",
      "SYNC.BACKFILL_SUCCEEDED",
      "SYNC.RETRY_REQUESTED",
      "SYNC.RETRY_SUCCEEDED",
      "SYNC.FAILED",
    ],
    failureStates: ["failure"],
  },
} as const satisfies Record<string, MachineBlueprint>;

export type RewriteMachineId = keyof typeof rewriteMachineMap;
